### PR TITLE
Adds C++03 implementation

### PR DESCRIPTION
**Pull request by palemieux**
Thanks to Cinecert for supporting this initial implementation.

### CODE REVIEW

**Comment by IMFTool** [comment]
Hi,
Building didn't work for me. (CMake 3.8.1, Apple LLVM version 5.0, MacOS 10.10.5)
Do any additional CMake values need to be set? 
Any other steps required upfront?

-Wolfgang

```
Wolfgangs-MacBook-Pro:build-debug wolfgangruppel$ make
Scanning dependencies of target regxmllibc
[  3%] Building CXX object CMakeFiles/regxmllibc.dir/src/main/cpp/com/sandflow/smpte/klv/KLVStream.cpp.o
/Users/wolfgangruppel/src/regxmllib-FEATURE-regxmllibc/regxmllib/src/main/cpp/com/sandflow/smpte/klv/KLVStream.cpp:269:16: error: duplicate explicit instantiation of
      'readTriplet'
template class basic_klvistream<char>;
               ^
/Users/wolfgangruppel/src/regxmllib-FEATURE-regxmllibc/regxmllib/src/main/cpp/com/sandflow/smpte/klv/KLVStream.cpp:39:39: note: previous explicit instantiation is here
template void basic_klvistream<char>::readTriplet(MemoryTriplet &t);
                                      ^
1 error generated.
make[2]: *** [CMakeFiles/regxmllibc.dir/src/main/cpp/com/sandflow/smpte/klv/KLVStream.cpp.o] Error 1
make[1]: *** [CMakeFiles/regxmllibc.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by palemieux** [comment]
@IMFTool Thanks for the bug report. Fixed at https://github.com/sandflow/regxmllib/pull/108/commits/49c221804eb37a5dffe2878520f12a6eaab83f22

**Comment by IMFTool** [comment]
I would suggest to add a namespace to avoid conflicts with names also used in asdcplib, in particular UL and UUID.
I assume several users may run into that problem.

**Comment by palemieux** [comment]
@IMFTool Good idea. I plan to use `rxml`.

**Pull request merged**
