### PR TITLE
Add support for reading Header Metadata from Footer partition

### LINKED ISSUE #84: Optionally read preface from Footer Partition
Perhaps this is already possible? If files are not Closed and Complete then the Footer Metadata can be much more useful than the Header Metadata. Therefore it would be very useful to be able to choose to read the Preface from the Footer instead.

### PR DESCRIPTION
**Pull request by palemieux**
Closes #84

### CODE REVIEW

**Comment by thomasheritage** [comment]
Thanks Pierre, this works very well.

Is it possible to make these two improvements?
* It would be very helpful to have a comment in the output Reg-XML that says whether the Header or the Footer was used (there are already many comments present which are very helpful e.g. source MXF file name, regxmllib build)
* At the moment the default behaviour is to read from the Header. However, a more helpful default behaviour would be as below (the default behaviour should be documented in the usage instructions along with the commandline arguments). This is because the Footer Header Metadata should be the most up-to-date available in the file because it's at the end. I would ignore all the Open/Closed Complete/Incomplete values because that's all very confusing and not always correctly used anyway (I don't think you are using these details at the moment so that's fine).
```
if HeaderMetadata in Footer:
   read from Footer
else:
  read from Header
```

**Comment by palemieux** [comment]
> I would ignore all the Open/Closed Complete/Incomplete values because that's all very confusing
> and not always correctly used anyway (I don't think you are using these details at the moment so that's fine).

Ah ok.

> if HeaderMetadata in Footer:

How does one test this? Presence of a preface?

**Comment by thomasheritage** [comment]
If there's Header Metadata in the Footer then it will have a Primer Pack and a Preface Set. So you could explicitly check for those. Or simply do a `try... except...` on reading from the Footer (regxmllib currently raises an exception if you try to read from the Footer and the MXF file does not have Header Metadata in the Footer).

**Comment by palemieux** [comment]
Ok. Will do.

**Comment by palemieux** [comment]
Implemented, ready for testing.

**Pull request merged**
