### PR TITLE
Added virtual destructor in Definition.h file

### PR DESCRIPTION
**Pull request by ethanchan747**

### CODE REVIEW

**Comment by palemieux** [comment]
@ethanchan747 Can you rebase your branch onto the head of master?

**Comment by ethanchan747** [comment]
done.

echan@Ethans-MacBook-Pro:~/lib/regxmllib$ git rebase -i a74c708ae554f6adf26f95da5831dcaab8084e36
[detached HEAD 8505f05] Changed CMakeList.txt to
 Author: echan <echan@localhost.localdomain>
 Date: Mon Aug 28 13:58:13 2017 -0700
 2 files changed, 5 insertions(+), 2 deletions(-)
Successfully rebased and updated refs/heads/master

**Comment by palemieux** [comment]
@ethanchan747 You have to do a `git pull` before the rebase. `master` is at adad4bc9946abacf95c76494ce63e08b181fedbc now.

**Comment by ethanchan747** [comment]
Please check if rebase worked. I did a git pull.

**Comment by palemieux** [comment]
Moved to https://github.com/sandflow/regxmllib/pull/114

**Pull request closed without merging**
